### ISSUE TITLE
Typechecker crashes on states.obs

### ISSUE THREAD

**Issue by mcoblenz** [mcoblenz/Obsidian#45]
[error] (run-main-0) java.util.NoSuchElementException: key not found: this
java.util.NoSuchElementException: key not found: this
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.immutable.TreeMap.default(TreeMap.scala:48)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.immutable.TreeMap.apply(TreeMap.scala:48)
	at edu.cmu.cs.obsidian.typecheck.Context.apply(Checker.scala:288)
	at edu.cmu.cs.obsidian.typecheck.Context.tableOfThis(Checker.scala:305)
	at edu.cmu.cs.obsidian.typecheck.Checker.edu$cmu$cs$obsidian$typecheck$Checker$$inferAndCheckExpr(Checker.scala:1017)
	at edu.cmu.cs.obsidian.typecheck.Checker.edu$cmu$cs$obsidian$typecheck$Checker$$checkStatement(Checker.scala:1533)
	at edu.cmu.cs.obsidian.typecheck.Checker$$anonfun$edu$cmu$cs$obsidian$typecheck$Checker$$checkStatementSequence$1.apply(Checker.scala:1244)
	at edu.cmu.cs.obsidian.typecheck.Checker$$anonfun$edu$cmu$cs$obsidian$typecheck$Checker$$checkStatementSequence$1.apply(Checker.scala:1243)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at edu.cmu.cs.obsidian.typecheck.Checker.edu$cmu$cs$obsidian$typecheck$Checker$$checkStatementSequence(Checker.scala:1243)
	at edu.cmu.cs.obsidian.typecheck.Checker.edu$cmu$cs$obsidian$typecheck$Checker$$checkTransactionInState(Checker.scala:1818)
	at edu.cmu.cs.obsidian.typecheck.Checker.edu$cmu$cs$obsidian$typecheck$Checker$$checkTransaction(Checker.scala:1871)
	at edu.cmu.cs.obsidian.typecheck.Checker$$anonfun$edu$cmu$cs$obsidian$typecheck$Checker$$checkContract$1.apply(Checker.scala:1943)
	at edu.cmu.cs.obsidian.typecheck.Checker$$anonfun$edu$cmu$cs$obsidian$typecheck$Checker$$checkContract$1.apply(Checker.scala:1941)
	at scala.collection.immutable.List.foreach(List.scala:393)
	at edu.cmu.cs.obsidian.typecheck.Checker.edu$cmu$cs$obsidian$typecheck$Checker$$checkContract(Checker.scala:1941)
	at edu.cmu.cs.obsidian.typecheck.Checker$$anonfun$checkProgram$1.apply(Checker.scala:1971)
	at edu.cmu.cs.obsidian.typecheck.Checker$$anonfun$checkProgram$1.apply(Checker.scala:1970)
	at scala.collection.immutable.List.foreach(List.scala:393)
	at edu.cmu.cs.obsidian.typecheck.Checker.checkProgram(Checker.scala:1970)
	at edu.cmu.cs.obsidian.typecheck.Checker.checkProgramAndPrintErrors(Checker.scala:1958)
	at edu.cmu.cs.obsidian.Main$.main(Main.scala:267)
	at edu.cmu.cs.obsidian.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by mcoblenz** [comment]
The issue is that inside the cases, `this` has type `readonly States.S1', but outside, `this` has type `owned States`. The common supertype is None, because of the readonly vs. owned distinction. 

It seems to me that `this` should always act as `owned` because it always carries typestate; is that not right? But making that change breaks the ParentPDT test because this assignment is not well-typed: `readonly UsesC a = this;` I think we should fix this by removing `readonly`, but then it still doesn't work because we need an owned UsesC, which we can't specify there.

Maybe this isn't worth fixing right now in light of the upcoming permissions changes, but I'm curious what the reasoning was. Tyler, can you weigh in?

**Comment by tyleretzel** [comment]
I don't agree that `this` should always act as `owned`: when reading `this` as a variable, the residual permission should be read, because ownership of `this` must be returned to the caller of the transaction afterwards. That's why the `readonly` is necessary in the ParentPDT test.

The problem is merely that the switch construct has a special case: when the thing being switched on is a variable, the typestate information in the context for the body of each of the cases changes according to the state specified in the case. For example, if I switch on `this` and have `case S { b }`, then `this` will be `C.S` in `b`.

This special case was implemented incorrectly in the case where the variable is `this`.

**Comment by mcoblenz** [comment]
Why is ‘this’ owned in the first place? We don’t want to enforce 
linearity (indeed, there’s special code elsewhere preventing that).

Thanks,
Michael

On 25 Aug 2017, at 0:15, Tyler Etzel wrote:

> I don't agree that `this` should always act as `owned`: when reading 
> `this` as a variable, the residual permission should be read, because 
> ownership of `this` must be returned to the caller of the transaction 
> afterwards. That's why the `readonly` is necessary in the ParentPDT 
> test.
>
> The problem is merely that the switch construct has a special case: 
> when the thing being switched on is a variable, the typestate 
> information in the context for the body of each of the cases changes 
> according to the state specified in the case. For example, if I switch 
> on `this` and have `case S { b }`, then `this` will be `C.S` in `b`.
>
> This special case was implemented incorrectly in the case where the 
> variable is `this`.
>
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mcoblenz/Obsidian/issues/45#issuecomment-324819702


Why

**Comment by mcoblenz** [comment]
Fixed with PR #46 .
